# Generated by Django 4.2.30 on 2026-06-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('truck_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('total_miles', models.FloatField(default=0.0)),
                ('total_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_route_geometry', models.TextField(db_column='route_geometry', default='[]')),
                ('_violations', models.TextField(db_column='violations', default='[]')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('driving_hours', models.FloatField(default=0.0)),
                ('duty_hours', models.FloatField(default=0.0)),
                ('rest_hours', models.FloatField(default=0.0)),
                ('_fuel_stops', models.TextField(db_column='fuel_stops', default='[]')),
                ('_remarks', models.TextField(db_column='remarks', default='[]')),
                ('_segments', models.TextField(db_column='segments', default='[]')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('pdf_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.tripday')),
            ],
        ),
    ]
